<?php

namespace Database\Seeders;

use App\Models\Journal;
use Illuminate\Database\Seeder;

class JournalSeeder extends Seeder
{
    public function run(): void
    {
        $journals = [
            [
                'title'          => 'Ilusi dan Persepsi: Ketika Pikiran Mengkhianati Dirinya Sendiri',
                'slug'           => 'ilusi-dan-persepsi',
                'published_date' => '2025-01-15',
                'content'        => "Seorang filsuf Yunani kuno, Plato, pernah menceritakan kisah manusia yang tinggal di dalam gua — terpenjara sejak lahir, hanya mampu melihat bayangan di dinding, dan meyakini bayangan itulah satu-satunya realitas. Ketika salah satu dari mereka keluar dan melihat matahari sesungguhnya, ia kembali ke dalam gua untuk berbagi kebenaran. Namun kawan-kawannya menertawakannya.\n\nInilah \"Alegori Gua\" Plato — dan inilah juga dasar dari sulap.\n\n**Persepsi Bukan Realitas**\n\nOtak manusia adalah mesin prediksi yang luar biasa. Ia tidak memproses seluruh informasi dari indera secara langsung; sebaliknya, ia mengambil \"jalan pintas\" berdasarkan pengalaman masa lalu. Ketika kita melihat sebuah kartu menghilang di tangan pesulap, otak kita tidak benar-benar \"melihat\" proses menghilangnya — otak kita memprediksi bahwa kartu itu masih ada, dan ketika prediksi itu salah, kita terpesona.\n\nIni disebut \"cognitive illusion\" — ilusi yang bukan ditipu oleh mata, melainkan oleh cara otak mengonstruksi realitas.\n\n**Seni Menyusun Narasi**\n\nPesulap besar bukan hanya ahli teknik — mereka adalah arsitek narasi. Setiap gerakan, setiap kata, setiap jeda adalah bagian dari sebuah cerita yang dirancang untuk memandu persepsi penonton. Seperti seorang novelis yang mengarahkan imajinasi pembaca, pesulap mengarahkan perhatian dan ekspektasi audiens.\n\nPsikolog Daniel Kahneman menyebut ada dua sistem berpikir manusia: Sistem 1 (cepat, intuitif, otomatis) dan Sistem 2 (lambat, analitis, penuh usaha). Sulap bekerja dengan \"menipu\" Sistem 1 sebelum Sistem 2 sempat bereaksi.\n\n**Pelajaran Filosofis**\n\nJika persepsi kita begitu mudah \"dibajak,\" betapa pentingnya kita selalu mempertanyakan asumsi dan keyakinan kita. Sulap, dalam konteks paling dalam, adalah undangan untuk rendah hati — pengingat bahwa apa yang kita lihat belum tentu merupakan keseluruhan kebenaran.\n\nSetiap pertunjukan adalah cermin yang memantulkan kembali kelemahan dan keajaiban kognisi manusia. Dan di situlah letak keindahannya.",
            ],
            [
                'title'          => 'Rahasia Keajaiban: Mengapa Manusia Mendambakan yang Mustahil',
                'slug'           => 'rahasia-keajaiban',
                'published_date' => '2025-02-03',
                'content'        => "Di setiap sudut kebudayaan manusia — dari dukun suku pedalaman hingga ilusionis panggung Las Vegas — selalu ada satu benang merah yang sama: hasrat terhadap keajaiban. Mengapa makhluk rasional seperti manusia begitu haus akan hal-hal yang secara logis tidak mungkin?\n\n**Psikologi Rasa Takjub (Awe)**\n\nPara peneliti psikologi dari UC Berkeley mendefinisikan \"awe\" (rasa takjub) sebagai emosi yang muncul ketika seseorang menghadapi sesuatu yang melampaui skema pemahaman mereka — sesuatu yang begitu besar atau luar biasa sehingga otak kita dipaksa untuk \"mengatur ulang\" cara kita memandang dunia.\n\nSulap adalah mesin pembangkit awe yang paling efisien. Dalam sepuluh detik, seorang pesulap mampu menciptakan momen yang memaksa penonton mempertanyakan hukum fisika, logika, dan realitas mereka sendiri.\n\n**Keajaiban Sebagai Kebutuhan Jiwa**\n\nPsikolog Abraham Maslow terkenal dengan piramida kebutuhannya. Namun ia juga menulis tentang \"peak experiences\" — momen-momen transenden di mana seseorang merasakan keterhubungan dengan sesuatu yang lebih besar dari dirinya sendiri. Pengalaman puncak ini, kata Maslow, adalah kebutuhan psikologis yang mendalam.\n\nPertunjukan sulap yang baik bisa menjadi salah satu jembatan menuju peak experience. Saat penonton menyaksikan sesuatu yang \"mustahil\" terjadi di depan mata mereka, ada sesuatu di dalam diri mereka yang melunak, terbuka, dan terasa hidup kembali.\n\n**Anak Kecil dalam Diri Kita**\n\nAda filosofi Jepang bernama \"Shoshin\" — pikiran pemula. Konsep ini mengajarkan bahwa mereka yang datang dengan pikiran terbuka, bebas dari asumsi, akan melihat lebih banyak keajaiban daripada yang datang dengan \"keahlian.\" Seorang anak kecil yang melihat pesulap untuk pertama kali mungkin mengalami keajaiban yang lebih dalam dari seorang profesor filsafat.\n\nSulap, di sini, berfungsi sebagai \"reset button\" — sebuah undangan untuk kembali menjadi pemula, untuk merasakan dunia seperti pertama kali melihatnya.",
            ],
            [
                'title'          => 'Fokus dan Kebebasan: Filosofi Konsentrasi dalam Seni Sulap',
                'slug'           => 'filosofi-fokus-dalam-sulap',
                'published_date' => '2025-03-10',
                'content'        => "Dalam tradisi Zen Buddhisme, ada sebuah konsep yang disebut \"Mushin\" — pikiran tanpa pikiran. Ini adalah kondisi di mana seorang seniman bela diri, musisi, atau meditator mencapai keadaan dimana gerakan mengalir tanpa hambatan pikiran sadar. Tidak ada keraguan, tidak ada analisis — hanya tindakan murni.\n\nBagi seorang pesulap, Mushin adalah cita-cita tertinggi.\n\n**Teknik dan Kebebasan**\n\nParadoks terbesar dalam seni sulap adalah ini: untuk menjadi bebas dan spontan di atas panggung, seorang pesulap harus pertama-tama menjadi budak dari latihan. Sebuah sleight of hand yang tampaknya alami dan effortless mungkin telah dilatih ribuan kali hingga gerakan itu menjadi \"otomatis\" — menjadi bagian dari tubuh.\n\nFilsuf Confucius pernah berkata: \"Pada usia tujuh puluh, aku bisa mengikuti apa yang hatiku inginkan, tanpa melanggar apa yang benar.\" Confucius tidak berbicara tentang sulap, tetapi ia berbicara tentang sesuatu yang sangat mirip — titik di mana disiplin bertahun-tahun telah begitu terinternalisasi sehingga kebebasan sejati menjadi mungkin.\n\n**Attention is the Rarest Form of Generosity**\n\nSimone Weil, filsuf Prancis, menulis bahwa \"perhatian adalah bentuk paling langka dan paling murni dari kemurahan hati.\" Seorang pesulap yang hebat meminta sesuatu yang sangat berharga dari penontonnya: waktu dan perhatian penuh mereka. Sebagai gantinya, ia menawarkan pengalaman yang tidak bisa dibeli atau dijelaskan.\n\nIni adalah kontrak yang bersifat sakral.\n\n**Misdirection: Seni Mengarahkan Pikiran**\n\nKonsep paling mendasar dalam sulap adalah misdirection — seni mengarahkan perhatian penonton ke tempat yang tidak relevan. Tetapi ini bukan sekadar trik; ini adalah studi mendalam tentang psikologi perhatian manusia.\n\nWilliam James, bapak psikologi Amerika, menulis: \"Kemampuan untuk memfokuskan kembali perhatian yang mengembara, berulang kali dan dengan sukarela, adalah akar dari penilaian, karakter, dan kehendak.\" Pesulap adalah master dari seni yang berlawanan — mereka mengarahkan perhatian orang lain. Dan dalam melakukannya, mereka mengajarkan kita seberapa rapuh dan seberapa mudah perhatian kita dibajak.",
            ],
            [
                'title'          => 'Topeng dan Identitas: Siapa Diri Kita di Balik Persona',
                'slug'           => 'topeng-dan-identitas',
                'published_date' => '2025-04-05',
                'content'        => "Kata \"person\" dalam bahasa Inggris berasal dari kata Latin \"persona\" — yang berarti topeng yang dikenakan oleh aktor Romawi kuno. Setiap aktor memakai topeng yang berbeda untuk setiap peran, dan penonton memahami bahwa topeng itu bukanlah wajah aktor yang sesungguhnya.\n\nApakah kita berbeda dari aktor-aktor itu?\n\n**Pesulap dan Persona**\n\nSetiap pesulap besar menciptakan sebuah \"persona\" — karakter yang lebih besar dari kehidupan nyata yang tampil di atas panggung. Houdini bukan sekadar pria bernama Erik Weisz; ia adalah \"The Handcuff King,\" simbol kebebasan dan pemberontakan terhadap batasan. David Copperfield bukan hanya seorang pesulap; ia adalah penyihir romantis yang membuat dunia tampak penuh kemungkinan.\n\nPersona ini bukan kebohongan — ia adalah ekspresi terkonsentrasi dari kebenaran tertentu tentang diri si pesulap. Seperti kata Carl Jung, persona adalah \"kompromi antara individu dan masyarakat tentang apa yang harus tampak.\"\n\n**Autentisitas di Balik Topeng**\n\nParadoksnya, seringkali justru melalui perannya — melalui topengnya — seorang seniman menemukan ekspresi paling otentiknya. Seorang komika yang tampil dengan karakter badut mungkin menyampaikan kebenaran paling dalam tentang kesedihan manusia, justru karena topeng badut itu memberinya \"jarak aman\" untuk berbicara jujur.\n\nDemikian pula seorang pesulap. Di balik jubah hitam dan topi silinder, ia mungkin menyampaikan sesuatu yang sangat nyata — kekaguman terhadap keindahan, kepercayaan bahwa dunia ini lebih luas dari yang kita kira, atau sekadar kegembiraan murni dari berbagi momen ajaib dengan orang lain.\n\n**Keajaiban Identitas**\n\nEksperimen psikologi menunjukkan bahwa ketika seseorang berpakaian seperti dokter, mereka cenderung berperilaku lebih berwibawa. Ketika seseorang berpakaian seperti seniman, mereka cenderung lebih kreatif. Ini dikenal sebagai \"enclothed cognition\" — identitas yang kita kenakan mempengaruhi cara kita berpikir dan bertindak.\n\nSiapa diri kita? Mungkin kita adalah jumlah dari semua topeng yang pernah dan sedang kita kenakan — dan mungkin, di suatu tempat di antara semua topeng itu, ada sesuatu yang tetap dan sungguh nyata.",
            ],
            [
                'title'          => 'Waktu dan Kekaguman: Ketika Pertunjukan Membuat Waktu Berhenti',
                'slug'           => 'waktu-dan-kekaguman',
                'published_date' => '2025-05-20',
                'content'        => "Pernahkah kamu benar-benar terpukau oleh sesuatu hingga tidak terasa waktu berlalu? Atau sebaliknya, pernahkah kamu duduk dalam kebosanan yang terasa seolah satu jam bisa terasa seperti satu hari?\n\nPengalaman subyektif waktu adalah salah satu fenomena paling misterius dalam psikologi manusia — dan pertunjukan sulap adalah laboratorium yang sempurna untuk mempelajarinya.\n\n**Waktu dalam Kondisi Awe**\n\nPenelitian oleh Melanie Rudd dari Stanford University menemukan bahwa ketika seseorang mengalami \"awe\" — rasa takjub yang mendalam — persepsi mereka tentang waktu melambat. Mereka merasakan seolah memiliki lebih banyak waktu, dan hal ini membuat mereka lebih sabar, lebih dermawan, dan lebih bahagia.\n\nSebuah pertunjukan sulap yang berhasil bisa menciptakan kondisi ini. Di momen puncak ketika penonton menyaksikan sebuah transformasi yang \"mustahil,\" waktu seolah berhenti.\n\n**Flow State: Keadaan Mengalir**\n\nMihaly Csikszentmihalyi, psikolog kenamaan, memperkenalkan konsep \"flow\" — kondisi di mana seseorang begitu tenggelam dalam sebuah aktivitas sehingga kesadaran diri menghilang dan waktu terasa berhenti. Seniman, atlet, musisi, dan pesulap semuanya mengejar kondisi ini.\n\nBagi penonton yang terpukau, flow berarti mereka hadir sepenuhnya — tidak memikirkan masa lalu atau masa depan, hanya momen ini.\n\n**Filosofi Kekinian**\n\nBanyak tradisi spiritual — dari Buddhisme Zen hingga Stoikisme Romawi — mengajarkan nilai \"hidup di saat ini.\" Marcus Aurelius menulis: \"Batasi dirimu pada saat ini.\" Pertunjukan sulap adalah salah satu cara paling efektif untuk memaksa penonton hadir sepenuhnya di saat ini.\n\nDalam dunia yang semakin terfragmentasi oleh notifikasi dan distraksi digital, mungkin inilah salah satu hadiah terbesar yang bisa diberikan seorang pesulap kepada penontonnya: beberapa menit di mana mereka benar-benar hadir.",
            ],
            [
                'title'          => 'Keberanian Menanggung Misteri: Seni Tidak Menjelaskan Segalanya',
                'slug'           => 'keberanian-menanggung-misteri',
                'published_date' => '2025-06-12',
                'content'        => "Kita hidup di zaman Google. Jika ada sesuatu yang tidak kita mengerti, kita cukup mengetikkannya dan dalam sepersekian detik, sebuah penjelasan muncul. Ketidaktahuan terasa seperti sesuatu yang harus segera diselesaikan, seperti bug dalam sistem yang harus di-patch.\n\nTetapi apakah ini cara yang sehat untuk hidup?\n\n**Teologi Apofatik: Kebenaran Melalui Ketidaktahuan**\n\nDalam tradisi teologi, ada sebuah pendekatan yang disebut \"apophatic\" — mendefinisikan realitas tertinggi bukan melalui apa yang ia adalah, melainkan melalui apa yang ia bukan. Karena realitas sejati terlalu luas untuk dikurung dalam kata-kata atau konsep.\n\nSeorang pesulap yang bijak memahami intuisi yang sama. Ketika diminta untuk menjelaskan sebuah trik, ia biasanya menolak — bukan karena takut rahasianya terbongkar, melainkan karena ia tahu bahwa penjelasan akan menghancurkan pengalaman. Beberapa hal memang lebih indah ketika tetap misterius.\n\n**Rilke: Cintailah Pertanyaannya**\n\nRainer Maria Rilke menulis kepada seorang pemuda: \"Saya ingin memohon Anda... untuk bersabar terhadap semua yang belum terpecahkan dalam hati Anda dan cobalah untuk mencintai pertanyaan-pertanyaan itu sendiri... Hiduplah dengan pertanyaan-pertanyaan itu sekarang.\"\n\nSulap mengajarkan ini. Sebuah pertunjukan yang baik tidak memberikan semua jawaban — ia meninggalkan penonton dengan pertanyaan yang indah yang bergema di benak mereka jauh setelah pertunjukan berakhir.\n\n**Toleransi terhadap Ambiguitas**\n\nPsikolog mengenal konsep \"tolerance for ambiguity\" — kemampuan untuk bertahan dalam kondisi ketidakpastian tanpa kecemasan berlebihan. Ini adalah karakteristik yang sangat berkorelasi dengan kreativitas dan kecerdasan emosional.\n\nSemakin sering kita membiarkan diri kita tersiram oleh misteri tanpa terburu-buru mencari penjelasan — semakin kita melatih toleransi ambiguitas kita. Seperti yang dikatakan Einstein: \"Misteri adalah hal paling indah yang bisa kita alami. Inilah sumber dari semua seni dan sains sejati.\"",
            ],
            [
                'title'          => 'Kepercayaan dan Kontrak Sakral: Hubungan Pesulap dan Penontonnya',
                'slug'           => 'kepercayaan-dan-kontrak-sosial',
                'published_date' => '2025-07-08',
                'content'        => "Ketika Anda duduk di kursi penonton, sebelum pertunjukan dimulai, sesuatu yang sangat menarik telah terjadi: Anda telah menandatangani sebuah kontrak tak tertulis.\n\nKontrak ini menyatakan bahwa Anda setuju untuk — setidaknya sementara — menangguhkan kecurigaan Anda. Bahwa Anda akan datang bukan sebagai detektif yang mencoba membongkar rahasia, melainkan sebagai penonton yang membiarkan diri Anda dibawa dalam sebuah perjalanan.\n\n**Coleridge dan Suspension of Disbelief**\n\nPenyair romantis Inggris, Samuel Taylor Coleridge, menciptakan istilah \"willing suspension of disbelief\" untuk menggambarkan kontrak tak tertulis antara penulis fiksi dan pembacanya. Penonton tahu bahwa pesulap adalah manusia biasa yang menggunakan keterampilan dan teknik — tetapi mereka memilih, untuk waktu pertunjukan, untuk membiarkan keajaiban itu nyata.\n\n**Kepercayaan Sebagai Fondasi**\n\nTanpa kepercayaan ini, pertunjukan sulap tidak mungkin. Seorang penonton yang datang dengan sikap \"saya akan membuktikan bahwa ini palsu\" tidak hanya menghancurkan pengalaman mereka sendiri, tetapi juga mengganggu pengalaman penonton lain di sekitarnya.\n\nSebaliknya, penonton yang datang dengan kepercayaan terbuka menciptakan energi kolektif yang justru membuat pesulap tampil lebih baik. Ada fenomena yang dikenal sebagai \"audience energy\" — pesulap terbaik di dunia akan mengakui bahwa kualitas penonton secara signifikan mempengaruhi kualitas pertunjukan.\n\n**Kontrak yang Timbal Balik**\n\nJika penonton memberikan kepercayaannya, pesulap berkewajiban untuk menghormati kepercayaan itu. Ini berarti memberikan pertunjukan yang tulus, terlatih, dan penuh dedikasi — bukan sekadar memperlihatkan \"trik.\"\n\nSeorang pesulap yang benar-benar menghormati penonton tidak akan pernah membuat penonton merasa bodoh atau ditipu. Sebaliknya, ia akan membuat mereka merasa seperti saksi dari sesuatu yang luar biasa — seperti mereka adalah bagian dari keajaiban itu sendiri.",
            ],
            [
                'title'          => 'Gagal dengan Anggun: Filosofi Ketabahan di Atas Panggung Kehidupan',
                'slug'           => 'gagal-dengan-anggun',
                'published_date' => '2025-08-01',
                'content'        => "Tidak ada yang lebih menakutkan bagi seorang pesulap dari satu kata ini: \"failure.\" Trik yang gagal di depan ratusan pasang mata. Kartu yang salah, cincin yang tidak mau lepas, merpati yang kabur ke arah yang salah.\n\nTetapi pesulap terbaik dunia tahu sesuatu yang tidak semua orang tahu: bagaimana Anda menghadapi kegagalan jauh lebih penting dari kegagalan itu sendiri.\n\n**Stoikisme dan Amor Fati**\n\nFilsuf Stoik seperti Marcus Aurelius dan Epiktetos mengajarkan bahwa kita tidak bisa selalu mengontrol apa yang terjadi kepada kita, tetapi kita selalu bisa mengontrol respons kita. Nietzsche mengembangkan ini menjadi konsep \"amor fati\" — cinta terhadap takdir. Bukan sekadar menerima apa yang terjadi, tetapi mencintainya, merangkulnya sebagai bagian dari perjalanan.\n\nKetika sebuah trik gagal di depan penonton, pesulap yang telah menginternalisasi amor fati tidak panik. Ia mengambil napas, tersenyum, dan mungkin — jika cukup berbakat — ia mengubah kegagalan itu menjadi bagian dari pertunjukan.\n\n**Fail Forward: Belajar dari Kejatuhan**\n\nThomas Edison dilaporkan pernah berkata tentang ribuan percobaannya menemukan bola lampu: \"Saya tidak gagal. Saya baru saja menemukan 10.000 cara yang tidak berhasil.\"\n\nSetiap kegagalan di panggung adalah data. Setiap trik yang tidak berhasil di sesi latihan adalah pelajaran. Pesulap profesional tidak menghindari kegagalan — mereka secara aktif mencari situasi di mana mereka bisa gagal, sehingga mereka bisa belajar dan tumbuh.\n\n**Cahaya Masuk Melalui Retakan**\n\nLeonard Cohen menulis dalam lagunya: \"Ada retak di segalanya / Itulah bagaimana cahaya masuk.\" Kerapuhan, ketidaksempurnaan, bahkan kegagalan — semua ini adalah tempat di mana cahaya bisa masuk.\n\nSeorang pesulap yang mampu gagal dengan anggun, yang bisa mengakui ketidaksempurnaan tanpa kehilangan kepercayaan dirinya — pesulap itu mengajarkan kepada penonton pelajaran yang jauh lebih berharga dari sekadar trik yang berhasil.\n\nKarena pada akhirnya, hidup itu sendiri adalah pertunjukan yang belum pernah ada \"rehearsal\" sempurnanya.",
            ],
        ];

        foreach ($journals as $j) {
            Journal::updateOrCreate(
                ['slug' => $j['slug']],
                [
                    'title'          => $j['title'],
                    'content'        => $j['content'],
                    'image_path'     => null,
                    'published_date' => $j['published_date'],
                ]
            );
        }

        $this->command->info('✅ 8 Jurnal Filosofi berhasil ditambahkan!');
    }
}

